# Site settings
title: NR's Awesome Title
email: junyuwu1992@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Literally my notes, and no much to say about it.
  I just feel bad left it empty.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  nrailgun

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
